# Generated by Django 5.2.3 on 2025-06-21 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_review', models.TextField()),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizzes.attempt')),
            ],
        ),
    ]
