# Generated by Django 5.2.3 on 2025-07-05 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_attempt_completed_at_alter_attempt_passed_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_feedback', to='quizzes.attempt'),
        ),
    ]
