# Generated by Django 5.2.3 on 2025-06-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='grade_level',
            field=models.CharField(choices=[('K', 'Kinder'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6')], default='3', max_length=2),
        ),
    ]
