# Generated by Django 4.2.23 on 2025-07-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_attempt_completed_at_alter_attempt_passed_and_more'),
        ('books', '0002_bookquiz_created_by_alter_bookquiz_created_for_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.child')),
            ],
        ),
        migrations.CreateModel(
            name='BookQuizAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='books.bookquizattempt')),
            ],
        ),
        migrations.DeleteModel(
            name='BookImage',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bookquiz',
            name='created_by',
        ),
        migrations.AddField(
            model_name='book',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.child'),
        ),
        migrations.AddField(
            model_name='book',
            name='grade_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='lexile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookquizquestion',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_images/books/'),
        ),
        migrations.AlterField(
            model_name='bookquiz',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookquiz',
            name='created_for_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.child'),
        ),
        migrations.AddField(
            model_name='bookquizattemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookquizquestion'),
        ),
        migrations.AddField(
            model_name='bookquizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookquiz'),
        ),
    ]
